name: Setup Python environment
description: Set up Python, install uv, sync dependencies
runs:
  using: composite
  steps:

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: 3.13
        activate-environment: true
        enable-cache: true
    - name: Sync project dependencies
      run: uv sync --locked --all-extras --dev
      shell: bash
